SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS APLICACAO_INSUMO;
DROP TABLE IF EXISTS INSUMO;
DROP TABLE IF EXISTS ATRIBUICAO_LOTE;
DROP TABLE IF EXISTS LOTE_CULTIVO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS GERENTE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS SETOR;

SET FOREIGN_KEY_CHECKS = 1;

-- 1. Espelho de CIDADE
CREATE TABLE SETOR (
    ID_SETOR INT AUTO_INCREMENT NOT NULL,
    COD_SETOR VARCHAR(10) UNIQUE NOT NULL,
    NOME_SETOR VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_SETOR PRIMARY KEY (ID_SETOR)
);

-- 2. Espelho de USUARIO (Gestão de Acesso)
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    COD_USUARIO VARCHAR(10) UNIQUE NOT NULL,
    NOME_USUARIO VARCHAR(50),
    EMAIL VARCHAR(100),
    SENHA VARCHAR(100),
    FOTO VARCHAR(200),
    TIPO INT DEFAULT 1 NOT NULL, -- 1(GERENTE), 2(FUNCIONARIO)
    ID_SETOR INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR) ON DELETE CASCADE
);

-- 3. Espelho de PROFESSOR
CREATE TABLE GERENTE (
    ID_GERENTE INT AUTO_INCREMENT NOT NULL,
    COD_GERENTE VARCHAR(10) UNIQUE NOT NULL,
    NOME_GERENTE VARCHAR(50),
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_GERENTE PRIMARY KEY (ID_GERENTE),
    CONSTRAINT FK_GERENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 4. Espelho de ALUNO
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT AUTO_INCREMENT NOT NULL,
    COD_FUNCIONARIO VARCHAR(10) UNIQUE NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50),
    IDADE INT,
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO),
    CONSTRAINT FK_FUNCIONARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 5. Espelho de DISCIPLINA (Entidade Principal)
CREATE TABLE LOTE_CULTIVO (
    ID_LOTE INT AUTO_INCREMENT NOT NULL,
    PERIODO INT, -- Ex: 2026 (Safra)
    NOME_LOTE VARCHAR(50),
    ID_GERENTE INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_LOTE PRIMARY KEY (ID_LOTE),
    CONSTRAINT FK_LOTE_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES GERENTE(ID_GERENTE) ON DELETE CASCADE
);

-- 6. Espelho de ALUNO_DISCIPLINA (Relação N:N)
CREATE TABLE ATRIBUICAO_LOTE (
    ID_ATRIBUICAO INT AUTO_INCREMENT NOT NULL,
    LOTE_ID INT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ATRIBUICAO PRIMARY KEY (ID_ATRIBUICAO),
    CONSTRAINT FK_ATRIBUICAO_LOTE FOREIGN KEY (LOTE_ID) REFERENCES LOTE_CULTIVO(ID_LOTE) ON DELETE CASCADE,
    CONSTRAINT FK_ATRIBUICAO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE
);

-- 7. Espelho de AVALIACAO
CREATE TABLE INSUMO (
    ID_INSUMO INT AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(100),
    LOTE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_INSUMO PRIMARY KEY (ID_INSUMO),
    CONSTRAINT FK_INSUMO_LOTE FOREIGN KEY (LOTE_ID) REFERENCES LOTE_CULTIVO(ID_LOTE) ON DELETE CASCADE
);

-- 8. Espelho de ALUNO_AVALIACAO (Relação N:N com valores)
CREATE TABLE APLICACAO_INSUMO (
    ID_APLICACAO INT AUTO_INCREMENT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    INSUMO_ID INT NOT NULL,
    QUANTIDADE DECIMAL(10,2), -- Espelho do campo "NOTA" (ex: 15.5 kg de adubo)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_APLICACAO PRIMARY KEY (ID_APLICACAO),
    CONSTRAINT FK_APLICACAO_FUNC FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
    CONSTRAINT FK_APLICACAO_INSUMO FOREIGN KEY (INSUMO_ID) REFERENCES INSUMO(ID_INSUMO) ON DELETE CASCADE
);

-- INSERÇÕES DE TESTE (População inicial)
INSERT INTO SETOR (COD_SETOR, NOME_SETOR) VALUES ('S01', 'Setor Norte'), ('S02', 'Setor Sul');

INSERT INTO USUARIO (COD_USUARIO, NOME_USUARIO, EMAIL, SENHA, TIPO, ID_SETOR) VALUES 
('U001', 'Carlos Silva', 'carlos@agm.com', '123456', 1, 1),
('U002', 'Ana Souza', 'ana@agm.com', '123456', 2, 2);

INSERT INTO GERENTE (COD_GERENTE, NOME_GERENTE, ID_USUARIO) VALUES ('G001', 'Carlos Silva', 1);
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO, NOME_FUNCIONARIO, IDADE, ID_USUARIO) VALUES ('F001', 'Ana Souza', 28, 2);

INSERT INTO LOTE_CULTIVO (PERIODO, NOME_LOTE, ID_GERENTE) VALUES (2026, 'Milho - Talhão A', 1);
INSERT INTO ATRIBUICAO_LOTE (LOTE_ID, FUNCIONARIO_ID) VALUES (1, 1);

INSERT INTO INSUMO (DESCRICAO, LOTE_ID) VALUES ('Adubo NPK 10-10-10', 1);
INSERT INTO APLICACAO_INSUMO (FUNCIONARIO_ID, INSUMO_ID, QUANTIDADE) VALUES (1, 1, 50.50);