-- ==========================================
-- SISTEMA AGM - ESTRUTURA DDL E INSERÇÕES
-- ==========================================
-- Versão: 2.0.0
-- MySQL / MariaDB
-- Execute este script para criar o banco
-- de dados e popular com dados de teste.
-- ==========================================

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS APLICACAO_INSUMO;
DROP TABLE IF EXISTS INSUMO;
DROP TABLE IF EXISTS ATRIBUICAO_LOTE;
DROP TABLE IF EXISTS LOTE_CULTIVO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS GERENTE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS SETOR;

SET FOREIGN_KEY_CHECKS = 1;

-- ==========================================
-- TABELAS
-- ==========================================

-- 1. Setores (Áreas da Fazenda)
CREATE TABLE SETOR (
    ID_SETOR INT AUTO_INCREMENT NOT NULL,
    COD_SETOR VARCHAR(10) UNIQUE NOT NULL,
    NOME_SETOR VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_SETOR PRIMARY KEY (ID_SETOR)
);

-- 2. Usuários (Gestão de Acesso Global)
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    COD_USUARIO VARCHAR(10) UNIQUE NOT NULL,
    NOME_USUARIO VARCHAR(50),
    EMAIL VARCHAR(100),
    SENHA VARCHAR(100),       -- bcrypt hash
    FOTO VARCHAR(200),
    TIPO INT DEFAULT 1 NOT NULL,  -- 1=GERENTE, 2=FUNCIONARIO
    STATUS_VALIDACAO BOOLEAN DEFAULT FALSE,
    RECOVERY_TOKEN VARCHAR(255),
    TOKEN_EXPIRES DATETIME,
    REFRESH_TOKEN VARCHAR(255),
    ID_SETOR INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR) ON DELETE CASCADE
);

-- 3. Gerentes (Extensão de Usuário)
CREATE TABLE GERENTE (
    ID_GERENTE INT AUTO_INCREMENT NOT NULL,
    COD_GERENTE VARCHAR(10) UNIQUE NOT NULL,
    NOME_GERENTE VARCHAR(50),
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_GERENTE PRIMARY KEY (ID_GERENTE),
    CONSTRAINT FK_GERENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 4. Funcionários (Extensão de Usuário)
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT AUTO_INCREMENT NOT NULL,
    COD_FUNCIONARIO VARCHAR(10) UNIQUE NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50),
    IDADE INT,
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO),
    CONSTRAINT FK_FUNCIONARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- 5. Lotes de Cultivo
CREATE TABLE LOTE_CULTIVO (
    ID_LOTE INT AUTO_INCREMENT NOT NULL,
    PERIODO INT,                     -- Ano da safra (ex: 2026)
    NOME_LOTE VARCHAR(50),
    ID_GERENTE INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_LOTE PRIMARY KEY (ID_LOTE),
    CONSTRAINT FK_LOTE_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES GERENTE(ID_GERENTE) ON DELETE CASCADE
);

-- 6. Atribuição: Funcionários designados para Lotes
CREATE TABLE ATRIBUICAO_LOTE (
    ID_ATRIBUICAO INT AUTO_INCREMENT NOT NULL,
    LOTE_ID INT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ATRIBUICAO PRIMARY KEY (ID_ATRIBUICAO),
    CONSTRAINT FK_ATRIBUICAO_LOTE FOREIGN KEY (LOTE_ID) REFERENCES LOTE_CULTIVO(ID_LOTE) ON DELETE CASCADE,
    CONSTRAINT FK_ATRIBUICAO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE
);

-- 7. Insumos disponíveis
CREATE TABLE INSUMO (
    ID_INSUMO INT AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(100),
    LOTE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_INSUMO PRIMARY KEY (ID_INSUMO),
    CONSTRAINT FK_INSUMO_LOTE FOREIGN KEY (LOTE_ID) REFERENCES LOTE_CULTIVO(ID_LOTE) ON DELETE CASCADE
);

-- 8. Aplicação: Quantidade de Insumo aplicada por Funcionário
CREATE TABLE APLICACAO_INSUMO (
    ID_APLICACAO INT AUTO_INCREMENT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    INSUMO_ID INT NOT NULL,
    QUANTIDADE DECIMAL(10,2),          -- Ex: 15.50 kg
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_APLICACAO PRIMARY KEY (ID_APLICACAO),
    CONSTRAINT FK_APLICACAO_FUNC FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
    CONSTRAINT FK_APLICACAO_INSUMO FOREIGN KEY (INSUMO_ID) REFERENCES INSUMO(ID_INSUMO) ON DELETE CASCADE
);

-- ==========================================
-- POPULAÇÃO DE TESTE
-- ==========================================
-- Senha de todos os usuários: 123456
-- Hash bcrypt gerado com bcryptjs (cost 10)
-- ==========================================

INSERT INTO SETOR (COD_SETOR, NOME_SETOR) VALUES 
('S01', 'Setor Norte'),
('S02', 'Setor Sul'),
('S03', 'Setor Leste'),
('S04', 'Setor Oeste'),
('S05', 'Setor Central'),
('S06', 'Setor Nordeste'),
('S07', 'Setor Noroeste'),
('S08', 'Setor Sudeste'),
('S09', 'Setor Sudoeste'),
('S10', 'Setor do Vale');

INSERT INTO USUARIO (COD_USUARIO, NOME_USUARIO, EMAIL, SENHA, TIPO, STATUS_VALIDACAO, ID_SETOR) VALUES 
('U001', 'Carlos Silva', 'carlos@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 1, TRUE, 1),
('U002', 'Ana Souza', 'ana@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 2),
('U003', 'Pedro Santos', 'pedro@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 3),
('U004', 'Marina Oliveira', 'marina@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 4),
('U005', 'João Pereira', 'joao@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 5),
('U006', 'Lucia Mendes', 'lucia@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 6),
('U007', 'Roberto Lima', 'roberto@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 7),
('U008', 'Fernanda Costa', 'fernanda@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 8),
('U009', 'Thiago Alves', 'thiago@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 9),
('U010', 'Camila Rocha', 'camila@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 10),
('U011', 'Gustavo Nunes', 'gustavo@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 1),
('U012', 'Patrícia Dias', 'patricia@agm.com', '$2b$10$0TsUVkzu5HH.pm1p14zoDOXP4X1QJ45nU4zVhNd1PIp6a2vGSLtkW', 2, TRUE, 2);

INSERT INTO GERENTE (COD_GERENTE, NOME_GERENTE, ID_USUARIO) VALUES 
('G001', 'Carlos Silva', 1);

INSERT INTO FUNCIONARIO (COD_FUNCIONARIO, NOME_FUNCIONARIO, IDADE, ID_USUARIO) VALUES 
('F001', 'Ana Souza', 28, 2),
('F002', 'Pedro Santos', 35, 3),
('F003', 'Marina Oliveira', 30, 4),
('F004', 'João Pereira', 42, 5),
('F005', 'Lucia Mendes', 27, 6),
('F006', 'Roberto Lima', 38, 7),
('F007', 'Fernanda Costa', 25, 8),
('F008', 'Thiago Alves', 33, 9),
('F009', 'Camila Rocha', 29, 10),
('F010', 'Gustavo Nunes', 31, 11),
('F011', 'Patrícia Dias', 26, 12);

INSERT INTO LOTE_CULTIVO (PERIODO, NOME_LOTE, ID_GERENTE) VALUES 
(2026, 'Milho - Talhão A', 1),
(2026, 'Soja - Talhão B', 1),
(2026, 'Milho - Talhão C', 1),
(2026, 'Feijão - Talhão D', 1),
(2026, 'Arroz - Talhão E', 1);

INSERT INTO ATRIBUICAO_LOTE (LOTE_ID, FUNCIONARIO_ID) VALUES 
(1, 1), (1, 2), (2, 3), (2, 4),
(3, 5), (3, 6), (4, 7), (4, 8),
(5, 9), (5, 10), (5, 11);

INSERT INTO INSUMO (DESCRICAO, LOTE_ID) VALUES 
('Adubo NPK 10-10-10', 1),
('Semente de Milho Híbrida', 1),
('Adubo NPK 20-05-15', 2),
('Semente de Soja Transgénica', 2),
('Fertilizante Orgânico', 3),
('Defensivo Agrícola', 3),
('Semente de Feijão Carioca', 4),
('Calcário', 4),
('Semente de Arroz Agulhinha', 5),
('Herbicida Pós-Emergente', 5);

INSERT INTO APLICACAO_INSUMO (FUNCIONARIO_ID, INSUMO_ID, QUANTIDADE) VALUES 
(1, 1, 50.50), (2, 2, 120.00), (3, 3, 80.00),
(4, 4, 200.00), (5, 5, 65.00), (6, 6, 15.00),
(7, 7, 90.00), (8, 8, 500.00), (9, 9, 150.00),
(10, 10, 25.00), (11, 1, 45.00);
